# Website details
name: Name
description: Description
email: email@site.com #EDIT!!!
author: author #EDIT!!!
lang: en
locale: en_US

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: America/New_York #EDIT!!!
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title  #EDIT!!! ???
baseurl: https://ozgrozer.github.io/dasper #EDIT!!!

# Includes   #ADD!!!
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications  #EDIT!!! wat is dit??
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"


# TO DO:
# - Remove "tr" languge sections (add dalk duits?)
# - Add "About" & "Contact" pages
